# -*- coding: utf-8 -*-
"""Filter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sKocllROYRFoPtjAYMiPW2jgqhoKV2n7
"""

b = ['Hi', 'how', 'are', 'you', 'James']
c = " ".join(b)
print(c)

a = ['apple', 'banana', 'cherry']   # list of words to exclude (case insensitive)
b = ['Apple', 'orange', 'Banana', 'grape', 'Cherry']
filtered_words = [word for word in b if word.lower() not in a]
print(filtered_words)

