# -*- coding: utf-8 -*-
"""NumpyShuffle.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zSmvQLjTGx5pb7XVB92ItPQOByYif8Wz
"""

import numpy as np
x = np.random.rand(10)# one dimension array
print(x)

import numpy as np
x = np.random.rand(100)# one dimension array
print(x)

#Shuffle
from numpy import random
import numpy as np
a= np.array([1, 2, 3, 4, 5])
random.shuffle(a)
print(a)