# -*- coding: utf-8 -*-
"""FradulenceDetection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zSmvQLjTGx5pb7XVB92ItPQOByYif8Wz
"""

from transformers import pipeline

# Specify the model name explicitly
model_name = "distilbert-base-uncased-finetuned-sst-2-english"
classifier = pipeline("text-classification", model=model_name)

# Use the classifier on your text
result = classifier("Meeting at 6 pm .")
print(result)


from transformers import pipeline

# Specify the model name explicitly
model_name = "distilbert-base-uncased-finetuned-sst-2-english"
classifier = pipeline("text-classification", model=model_name)

# Use the classifier on your text
result = classifier("Credit card CVV required")
print(result)


from transformers import pipeline

# Specify the model name explicitly
model_name = "distilbert-base-uncased-finetuned-sst-2-english"
classifier = pipeline("text-classification", model=model_name)

# Use the classifier on your text
result = classifier("Cretid card CVV required")[0]
print(result)
s = result['score']
l = result['label']

# Print the results
print("Score:" ,s)
print("Label:" ,l)