# -*- coding: utf-8 -*-
"""PromptGenerateText.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zSmvQLjTGx5pb7XVB92ItPQOByYif8Wz
"""

import warnings
from transformers import pipeline

# Suppress warning messages
warnings.filterwarnings("ignore")

# Load text generation pipeline
text_generator = pipeline("text-generation", model="gpt2")

# Generate text with `pad_token_id` set explicitly
generated_output = text_generator("Java is", pad_token_id=50256)

# Extract and print the generated text only
generated_text = generated_output[0]['generated_text']
print(generated_text)

#prompt genrate txt
from transformers import pipeline

# Load text generation pipeline
text_generator = pipeline("text-generation", model="gpt2")

# Generate text
generated_text = text_generator("Once upon a time")
print(generated_text)

#prompt genrate txt
from transformers import pipeline
with open("generated_text.txt", "w") as file:
  text_generator = pipeline("text-generation", model="gpt2")
  generated_text = text_generator("Once upon a time")
  file_text=generated_text[0]['generated_text']
  file.write(file_text)