# -*- coding: utf-8 -*-
"""AddwordsNltk.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pDQW6wdi335YLBtqEO_WofoA3EWuWmbw
"""

#add words
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

# Download NLTK stopwords
nltk.download('stopwords')
nltk.download('punkt')

# Define the input sentence
input_sentence = input("Enter =")

# Tokenize the input sentence
tokens = word_tokenize(input_sentence)

# Get English stopwords
stop_words = set(stopwords.words('english'))

# Add custom stopwords
additional_stopwords = ["leading", "platform", "building","hi"]
stop_words.update(additional_stopwords)

# Remove stopwords
filtered_tokens = [word for word in tokens if word.lower() not in stop_words]

# Join the filtered tokens back into a sentence
filtered_sentence = " ".join(filtered_tokens)

print("Original Sentence:")
print(input_sentence)
print("\nFiltered Sentence:")
print(filtered_sentence)