# -*- coding: utf-8 -*-
"""nltkupperlowerpuntuation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pDQW6wdi335YLBtqEO_WofoA3EWuWmbw
"""

import nltk
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('averaged_perceptron_tagger')
from nltk.tokenize import word_tokenize

# Ensure NLTK's tokenizer is downloaded
nltk.download('punkt')

#Lower
b=input("Enter a text")
x1=b.lower()
print(x1)

#upper
b1=input("Enter a text")
x2=b1.upper()
print(x2)

#title
b2=input("Enter a text")
x3=b2.title()
print(x3)

#puntuation
import re
x11=input("Enter a text=")
# Use regular expression to remove punctuation
a1 = re.sub(r'[^\w\s]', '', x11)

print(a1)