# -*- coding: utf-8 -*-
"""nltk.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pDQW6wdi335YLBtqEO_WofoA3EWuWmbw
"""

import re

text = " ".join(x)
print(text)

import nltk
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('averaged_perceptron_tagger')




import nltk
from nltk.tokenize import word_tokenize

# Ensure NLTK's tokenizer is downloaded
nltk.download('punkt')

a = "Hi how are you"
tokens = word_tokenize(a)
print(tokens)