# -*- coding: utf-8 -*-
"""Nltkfiltertokenjoin.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pDQW6wdi335YLBtqEO_WofoA3EWuWmbw
"""

import nltk
from nltk.tokenize import word_tokenize

text = "hi I am balamurugan"
filter = ("hi", "i", "am")

tokens = word_tokenize(text)
filtered_tokens = [token for token in tokens if token not in filter]

filtered_text = ' '.join(filtered_tokens)
print(filtered_text)