# -*- coding: utf-8 -*-
"""reRemoveextrawhitespace.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pDQW6wdi335YLBtqEO_WofoA3EWuWmbw
"""

#Remove Extra Whitespaces
import re
text = input("Input =")
a12=re.sub(r'\s+', ' ', text).strip()
print(a12)