# -*- coding: utf-8 -*-
"""reremovenumbers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pDQW6wdi335YLBtqEO_WofoA3EWuWmbw
"""

import re # remove numbers
text = input("Input =")
a=re.sub(r'\d+', '', text)
print(a)