# -*- coding: utf-8 -*-
"""reSpecialChar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pDQW6wdi335YLBtqEO_WofoA3EWuWmbw
"""

#Special cha
import re
text = input("Input =")
a12=re.sub(r'[^A-Za-z0-9\s]+', '', text)
print(a12)