# -*- coding: utf-8 -*-
"""Pil.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zSmvQLjTGx5pb7XVB92ItPQOByYif8Wz
"""

from PIL import Image
im = Image.open("cat.jpg")
#Show actual Image
display(im)