# -*- coding: utf-8 -*-
"""Functionswithreturn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sKocllROYRFoPtjAYMiPW2jgqhoKV2n7
"""

def add():
   x=2
   y=4
   c=x+y
   print("add=",c)
   return c
def sub():
    x=2
    y=4
    c1=x-y
    print("sub=",c1)
    return c1
z=add()
print(z)
z1=sub()
print(z1)

