# -*- coding: utf-8 -*-
"""BGR2RGB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zSmvQLjTGx5pb7XVB92ItPQOByYif8Wz
"""

import cv2
import matplotlib.pyplot as plt
img = cv2.imread('zebra.jpg')

# Convert BGR image to RGB for displaying with matplotlib
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

# Display the image with matplotlib
plt.imshow(img)
plt.axis('off')
plt.show()