# -*- coding: utf-8 -*-
"""FuzzyBasicCode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sKocllROYRFoPtjAYMiPW2jgqhoKV2n7
"""

#pip install fuzzywuzzy
#pip install python-Levenshtein
#conda install -c conda-forge fuzzywuzzy
#conda install -c conda-forge python-levenshtein
import Levenshtein as lev
Str1 = "Good Morning"
Str2 = "Good Morning"
Distance = lev.distance(Str1.lower(),Str2.lower()),
print(Distance)

import Levenshtein as lev
Str1 = "Good Morning"
Str2 = "Good morning"
Distance = lev.distance(Str1.lower(),Str2.lower()),
print(Distance)

import Levenshtein as lev
Str1 = "Good "
Str2 = "Good Morning"
Distance = lev.distance(Str1.lower(),Str2.lower()),
print(Distance)

import Levenshtein as lev
Str1 = "Cat"
Str2 = "Dog"
Distance = lev.distance(Str1.lower(),Str2.lower()),
print(Distance)

import Levenshtein as lev
Str1 = "Movie"
Str2 = "Rajini"
Distance = lev.distance(Str1.lower(),Str2.lower()),
print(Distance)

import Levenshtein as lev
Str1 = "Good "
Str2 = "Hi Good Morning"
Distance = lev.distance(Str1.lower(),Str2.lower()),
print(Distance)

from fuzzywuzzy import fuzz
from fuzzywuzzy import process
s1 = "Good Morning"
s2 = "hi gud morning"
b=fuzz.WRatio(s1, s2)
print (("\nFuzzy WRatio: "), b)

from fuzzywuzzy import fuzz
from fuzzywuzzy import process
s1 = "I am  bala"
s2 = "My name is   bala"
b=fuzz.WRatio(s1, s2)
print (("\nFuzzy WRatio: "), b)

from fuzzywuzzy import fuzz
from fuzzywuzzy import process
s1 = "Cat"
s2 = "dog"
b=fuzz.WRatio(s1, s2)
print (("\nFuzzy WRatio: "), b)


from fuzzywuzzy import fuzz
from fuzzywuzzy import process
s1 = "Cat"
s2 = "taC"
b=fuzz.WRatio(s1, s2)
print (("\nFuzzy WRatio: "), b)


from fuzzywuzzy import fuzz
from fuzzywuzzy import process
s1 = "I want mobile"
s2 = "Samsung"
b=fuzz.WRatio(s1, s2)
print (("\nFuzzy WRatio: "), b)


from fuzzywuzzy import fuzz
from fuzzywuzzy import process
s1 = "I want mobile"
s2 = "Nokia"
b=fuzz.WRatio(s1, s2)
print (("\nFuzzy WRatio: "), b)


from fuzzywuzzy import fuzz
from fuzzywuzzy import process
s1 = "I want mobile"
s2 = "mobile"
b=fuzz.WRatio(s1, s2)
print (("\nFuzzy WRatio: "), b)


from fuzzywuzzy import fuzz
from fuzzywuzzy import process
s1 = "movie"
s2 = "Super Star"
b=fuzz.WRatio(s1, s2)
print (("\nFuzzy WRatio: "), b)

from fuzzywuzzy import fuzz
from fuzzywuzzy import process
s1 = 4
s2 = 4
b=fuzz.WRatio(s1, s2)
print (("\nFuzzy WRatio: "), b)



from fuzzywuzzy import fuzz
from fuzzywuzzy import process
s1 = "11113"
s2 = "4"
b=fuzz.WRatio(s1, s2)
print (("\nFuzzy WRatio: "), b)

pip install fuzzywuzzy

