# -*- coding: utf-8 -*-
"""ForLoop.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sKocllROYRFoPtjAYMiPW2jgqhoKV2n7
"""

#for
for x in range(5):  #start at 0 end before 5 increment by 1
    print(x)


for x in range(5):  #start at 0 end before 5 increment by 1
    print("hi")

