# -*- coding: utf-8 -*-
"""Streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zSmvQLjTGx5pb7XVB92ItPQOByYif8Wz
"""

Check box



import streamlit as st



# Main Streamlit app

st.title("Checkbox Example")



# Create a checkbox using st.checkbox()

checked = st.checkbox("Check me")



# Check if the checkbox is selected

if checked:

    st.write("Checkbox is selected!")

else:

    st.write("Checkbox is not selected.")

import streamlit as st

# Set the title of the application

st.title("My Streamlit App")



# Display a section heading

st.title("Section 1")



# Display a subheading

st.title("Subsection 1.1")


streamlit run app.py

import streamlit as st



# Create columns with st.columns()

col1, col2 = st.columns(2)



# Add content to the first column

with col1:

    st.header("Column 1")

    st.write("This is the content of column 1.")



# Add content to the second column

with col2:

    st.header("Column 2")

    st.write("This is the content of column 2.")



# You can continue adding more content outside the columns

st.write("Content outside columns.")

import streamlit as st



def home_page():

    st.title("Home Page")

    st.write("Welcome to the Home Page!")

    # Add content for the home page



def about_page():

    st.title("About Page")

    st.write("Welcome to the About Page!")

    # Add content for the about page





st.sidebar.title("Navigation")

pages = ["Home", "About"]

selection = st.sidebar.selectbox("Go to", pages)



if selection == "Home":

        home_page()

elif selection == "About":

        about_page()