# -*- coding: utf-8 -*-
"""pilrotateblurzoom.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zSmvQLjTGx5pb7XVB92ItPQOByYif8Wz
"""

from PIL import Image
im = Image.open("cat.jpg")
#Show actual Image
display(im)


#rotate and save
from PIL import Image
im = Image.open("cat.jpg")

display(im)
#Show rotated Image
im = im.rotate(45)
display(im)
im.save("cat0.jpg")



#blur
from PIL import Image, ImageFilter
a = Image.open('cat.jpg')
blurImage = a.filter(ImageFilter.BLUR)
display(blurImage)
#Save blurImage
blurImage.save('cat1.jpg')


from PIL import Image
im = Image.open("cat.jpg")
original_size = im.size  # (width, height)
new_size = (original_size[0] * 2, original_size[1] * 2)
im_resized = im.resize(new_size)
im_resized.save("cat_resized.jpg")
zoom=Image.open("cat_resized.jpg")
display(zoom)