# -*- coding: utf-8 -*-
"""String.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sKocllROYRFoPtjAYMiPW2jgqhoKV2n7
"""

a=" good morning"
b=a.upper()
print(b)


a=" good morning"
b=a.upper()
print(b)


a=" HI HOW ARE YOU"
b=a.title()
print(b)

ip=input("Enter =")
a=ip.lower()
b=ip.upper()
c=ip.title()
print("Lower Format =",a)
print("Upper Format=",b)
print("Title Format=",c)

