# -*- coding: utf-8 -*-
"""ArrayToImage.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zSmvQLjTGx5pb7XVB92ItPQOByYif8Wz
"""

#array to image
from PIL import Image
import numpy as np
img = Image.fromarray(img_arr)
display(img)
img.save("RGB_image.jpg")