# -*- coding: utf-8 -*-
"""arraynumpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sKocllROYRFoPtjAYMiPW2jgqhoKV2n7
"""

import numpy as np

arr = np.array(["a", "b", "c", "d", "e"])

print(arr)