# -*- coding: utf-8 -*-
"""forminganarray.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sKocllROYRFoPtjAYMiPW2jgqhoKV2n7
"""

#Dynamic array
import numpy as np
x = int(input("Enter x? "));
y = int(input("Enter y? "));
z = int(input("Enter z? "));
a = np.array([x,y,z])
b = np.array([z,y,x])
c = a*b;
print(a)
print(b)
print(c)

