# -*- coding: utf-8 -*-
"""forminganarray.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sKocllROYRFoPtjAYMiPW2jgqhoKV2n7
"""

#Forming a array from a array
import numpy as np

arr = np.array([0,1, 2, 3, 4])

a=(arr[0])
b=(arr[1])
c=(arr[2])
d=(arr[3])
e=(arr[4])
x=np.array([e,a, c, b, b])
y=np.array([a,a, a, a, a])
z=np.array([b,a, b, d, a])
print(x)
print(y)
print(z)

