# -*- coding: utf-8 -*-
"""getinputfromuser.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sKocllROYRFoPtjAYMiPW2jgqhoKV2n7
"""

a = int(input("Enter a integer = "));
b = float(input("Enter a decimal value ="));
c = input("Enter a string = ");
print(a)
print(b)
print(c)