# -*- coding: utf-8 -*-
"""getvaluefromarrayusingindex.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sKocllROYRFoPtjAYMiPW2jgqhoKV2n7
"""

import numpy as np

arr = np.array([0,1, 2, 3, 4, 5, 6, 7])
x=arr[2:4]
print(x)
y=arr[4:]
print(y)
z=arr[:4]
print(z)

