# -*- coding: utf-8 -*-
"""getvaluefromarrayusingindex.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sKocllROYRFoPtjAYMiPW2jgqhoKV2n7
"""

#Indexing
import numpy as np

arr = np.array([1, 2, 3, 4])

d=arr[-2]
e=arr[-3]
f1=arr[-1]
f=d+e
print(c)
print(f)
print(f1)