# -*- coding: utf-8 -*-
"""getvaluefromarrayusingindex.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sKocllROYRFoPtjAYMiPW2jgqhoKV2n7
"""

#Indexing
import numpy as np

arr = np.array([1, 2, 3, 4])
c=arr[0]
d=arr[1]
e=arr[2]
f=d+e
print(f)