# -*- coding: utf-8 -*-
"""greaterthanlessthan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sKocllROYRFoPtjAYMiPW2jgqhoKV2n7
"""

a=20
b=20
c=a+b
g=a>=b
print("a>=b=",g)
m=a<=b
print("a<=b=",m)
n=a>b
print("a>=b=",n)
o=a<b
print("a<b=",o)
j=a==b
j1=a!=b
print("a==b=",j)
print("not equal-",j1)