# -*- coding: utf-8 -*-
"""maths+to/.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sKocllROYRFoPtjAYMiPW2jgqhoKV2n7
"""

#math
a=10
b=20
c=a-b
d=a+b
e=a/b
f=a*b
g=a**b#a power b
print(g)