# -*- coding: utf-8 -*-
"""minmaxvaluefromarray.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sKocllROYRFoPtjAYMiPW2jgqhoKV2n7
"""

#min and max
import numpy as np

arr = np.array([0, 12, 1, 3, 4, 5, 6])
min=np.min([arr])
max=np.max([arr])
print(min)
print(max)

