# -*- coding: utf-8 -*-
"""performmathsoperationonarray.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sKocllROYRFoPtjAYMiPW2jgqhoKV2n7
"""

import numpy as np
a = np.array([1,2,3,4,5,6])
b = np.array([2,1,1,1,12,9])
c = a+b;
print(a)
print(b)
print(c)