# -*- coding: utf-8 -*-
"""reverseaarray.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sKocllROYRFoPtjAYMiPW2jgqhoKV2n7
"""

#Reverse an array
import numpy as np

x = np.array([12, 38,65,87,67])

ra= np.flip(x)
print(ra)

