# -*- coding: utf-8 -*-
"""roundofvaluesinarray.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sKocllROYRFoPtjAYMiPW2jgqhoKV2n7
"""

#Round off

import numpy as np
arr = np.array([41.25, 42.32, 43.25, 44.9])
arr1 = np.around(arr, 1)
print(arr1)


#Round off
import numpy as np
arr = np.array([41.25, 42.32, 43.65, 44.9999])
arr1 = np.around(arr, 0)
print(arr1)

import numpy as np
arr = np.array([41.25, 42.9, 43.25, 44])
arr1 = np.ceil([arr])
arr2=np.floor([arr])
print("Ceil=",arr1)
print("Floor=",arr2)

