# -*- coding: utf-8 -*-
"""sizeofarray.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sKocllROYRFoPtjAYMiPW2jgqhoKV2n7
"""

import numpy as np
b = np.array([1, 2, 3, 4, 5])
x=b.size
print(x)

