# -*- coding: utf-8 -*-
"""sortinganarray.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sKocllROYRFoPtjAYMiPW2jgqhoKV2n7
"""

# sorting a array
import numpy as np

arr = np.array([0, 12, 1, 3, 4, 5, 6])
print("Original array:")
print(arr)
arr1 = np.sort(arr)
print(arr1)
ra= np.flip(arr1)
print(ra)

