# -*- coding: utf-8 -*-
"""spaceusing\nE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sKocllROYRFoPtjAYMiPW2jgqhoKV2n7
"""

#to print with space
A=10
B=5
C= 8
E="Jan2023"
print(A)
print("\nE=",E)#space