# -*- coding: utf-8 -*-
"""summeanofarray.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sKocllROYRFoPtjAYMiPW2jgqhoKV2n7
"""

import numpy as np
arr = np.array([1, 2, 3, 5, 9])
sum=np.sum([arr])
mean=np.mean([arr])
print(sum)
print(mean)

