# -*- coding: utf-8 -*-
"""matlabplotgraph5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sKocllROYRFoPtjAYMiPW2jgqhoKV2n7
"""

#bar
from matplotlib import pyplot as plot
x = [10, 20, 30,40,50,60]
y = [100, 200, 300,400,500,600]
plot.bar(x, y,color='red')
plot.title('L graph')
plot.ylabel('Y axis')
plot.xlabel('X axis')
plot.show()

