# -*- coding: utf-8 -*-
"""matlabplotgraph1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sKocllROYRFoPtjAYMiPW2jgqhoKV2n7
"""

df.plot(kind = 'scatter', x = 'A', y = 'B',  color = 'red')

df.plot(kind = 'line', x = 'A', y = 'B',  color = 'red')

df.plot(kind = 'area', x = 'A', y = 'B',  color = 'red')

df.plot(kind = 'bar', x= 'A', y= 'B', color = 'red')

