# -*- coding: utf-8 -*-
"""matlabplotgraph.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sKocllROYRFoPtjAYMiPW2jgqhoKV2n7
"""

import pandas as pd
from matplotlib import pyplot as plot

# read by default 1st sheet of an excel file
df = pd.read_excel('plot.xlsx')

df.plot(kind = 'line', x= 'A', y= 'B', color = 'red')

# set the title
plot.title('Line')
plot.savefig('line.pdf')
# show the plot
plot.show()

