# -*- coding: utf-8 -*-
"""Yolo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zSmvQLjTGx5pb7XVB92ItPQOByYif8Wz
"""

from ultralytics import YOLO
import cv2
import matplotlib.pyplot as plt
model = YOLO('yolov8n.pt')

results = model('/content/mobile.jpg')

# Extract the first result (since we're processing one image)
result = results[0]

# Initialize a dictionary to count object occurrences
object_counts = {}

# Loop through each detected object
for box in result.boxes:
    class_index = int(box.cls.item())  # Class index
    class_name = result.names[class_index]  # Class name
    # Increment the count for the detected class
    object_counts[class_name] = object_counts.get(class_name, 0) + 1

# Create a summary string for the detections
a = ', '.join([f"{count} {name}" for name, count in object_counts.items()])

# Print the summary string
print(a)

if 'book' in a:
    print("The word 'book' is in the list.")
else:
    print("The word 'book' is not in the list.")


# Search for the word 'book'
if 'axe' in a:
    print("The word 'axe' is in the list.")
else:
    print("The word 'axe' is not in the list.")