# -*- coding: utf-8 -*-
"""listslice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sKocllROYRFoPtjAYMiPW2jgqhoKV2n7
"""

#Print the second item of the list:
thislist = ["apple", "banana", "cherry"]
a=thislist[1]
print(a)


#Print the second item of the list:
thislist = ["apple", "banana", "cherry"]
a1=thislist[0]
print(a1)

#Print the second item of the list:
thislist = ["apple", "banana", "cherry"]
a3=thislist[2]
print(a3)

