# -*- coding: utf-8 -*-
"""listlength.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sKocllROYRFoPtjAYMiPW2jgqhoKV2n7
"""

x = ["apple", "banana", "cherry"]
a=len(x)
print(a)

