# -*- coding: utf-8 -*-
"""listslice1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sKocllROYRFoPtjAYMiPW2jgqhoKV2n7
"""

#Replace a Element
thislist = ["apple", "banana", "cherry"]
thislist[1] = "kiwi"
print(thislist)

thislist = ["apple", "banana", "cherry", "orange", "kiwi", "mango"]
thislist[1:3] = ["kiwi", "watermelon"]
print(thislist)

thislist = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
a=thislist[2:5]
print(a)
#start from 2 till 5


thislist = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
a=thislist[:4]
print(a)
#start from 0 till 4


thislist = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
x=thislist[2:]
print(x)
# from 2 everything

A = ["apple", "banana", "cherry"]
print(A)

#String, int and boolean data types:
list1 = ["apple", "banana", "cherry"]
list2 = [1, 5, 7, 9, 3]
list3 = [True, False, False]
list4 = ["abc", 34, True, 40, "male"]

