# -*- coding: utf-8 -*-
"""listadddeletereplaceallfunction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sKocllROYRFoPtjAYMiPW2jgqhoKV2n7
"""

thislist = ["apple", "banana", "cherry"]
thislist.insert(2, "watermelon")
print(thislist)


#append
thislist = ["apple", "banana", "cherry"]
thislist.append("orange")
print(thislist)

#Remove
thislist = ["apple", "banana", "cherry"]
thislist.pop(1)
print(thislist)


#Remove "banana":
thislist = ["apple", "banana", "cherry","banana"]
thislist.remove("banana")
print(thislist)

#Sorting

thislist = [9,10,11,89,0,2,3,4]

thislist.sort()
print(thislist)


#Sorting
thislist = ["orange", "mango", "kiwi", "pineapple", "banana"]
thislist.sort()
print(thislist)

#Dcending Sort
thislist = [9,10,11,89,0,2,3,4]
thislist.sort(reverse = True)
print(thislist)

thislist = ["apple", "banana", "cherry"]
tropical = ["mango", "pineapple", "papaya"]
thislist.extend(tropical)
print(thislist)

#Extend using +

list1 = ["a", "b", "c"]
list2 = [1, 2, 3]

list3 = list1 + list2
print(list3)


#Extend using +

list1 = [4, 5, 6]
list2 = [1, 2, 3]

list3 = list1 + list2
print(list3)

