# -*- coding: utf-8 -*-
"""CroppingImage.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zSmvQLjTGx5pb7XVB92ItPQOByYif8Wz
"""

#Cropping a image

#Import required Image library
from PIL import Image
#Create an Image Object from an Image
im = Image.open('cat.jpg')
#Display actual image
im.show()
#left, upper, right, lowe
#Crop
cropped = im.crop((1,2,300,300))
#Display the cropped portion
cropped.show()
#Save the cropped image
cropped.save('star5.jpg')