# -*- coding: utf-8 -*-
"""FilterAndJoin.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sKocllROYRFoPtjAYMiPW2jgqhoKV2n7
"""

a = ['apple', 'banana', 'cherry']   # list of words to exclude (case insensitive)
b = ['Apple', 'orange', 'Banana', 'grape', 'Cherry']
filtered_words = [word for word in b if word.lower() not in a]
print(filtered_words)
a = ["what", "how", "why","is","in","your"]#only lower case


ip= input("Enter your sentence: ")
l=ip.lower()
print("\ninput in lower case =",l)
# Split the input string into individual words
b = l.split()
print("\ninput in list Format=",b)

# Create a new list without the words to remove
filter = [word for word in b if word.lower() not in a]
print("\nfiltered words=",filter)
# Join the filtered words back together
result = " ".join(filter)
print("\nKey word=", result)

