# -*- coding: utf-8 -*-
"""OpenImageUsingModule.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zSmvQLjTGx5pb7XVB92ItPQOByYif8Wz
"""

#Open image using Image module cv2_imshow()
from PIL import Image
im = Image.open("cat.jpg")
#Show actual Image
display(im)
#Show rotated Image
im = im.rotate(45)
display(im)
im.save("cat0.jpg")