# -*- coding: utf-8 -*-
"""Getspecificdatafromexcelsheet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sKocllROYRFoPtjAYMiPW2jgqhoKV2n7
"""

import pandas as pd

df = pd.read_excel("mark.xlsx")
#df = pd.read_csv("mark.csv")
q1=df.query('Math > 90')
print(" Math > 90\n",q1)
q2=df.query('Math > 90 and Phy >90')
print(q2)
q3=df.query('Math > 90 and Phy >90 and Eng >90')
print(q3)
q4=df.query('Math > 90 and Phy >90 and Eng >90 and Che>90')
print(q4)
q5=df.query('Math == 90 or Phy ==90 or Eng ==90 or Che==90')
print(q5)
q5=df.query('Math == 91')
print(q5)

