# -*- coding: utf-8 -*-
"""readdatafromexcelandsortdatainascendingordescending.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sKocllROYRFoPtjAYMiPW2jgqhoKV2n7
"""

import pandas as pd

df = pd.read_excel("mark.xlsx")
#df = pd.read_csv("mark.csv")
print(df)
sort=df.sort_values(by=["Math"])
print(sort)
dsort=df.sort_values(by='Math', ascending=False)
print(dsort)

