# -*- coding: utf-8 -*-
"""Readdatafromexcelandcsv.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sKocllROYRFoPtjAYMiPW2jgqhoKV2n7
"""

import pandas as pd

df = pd.read_excel("mark.xlsx")
#df = pd.read_csv("mark.csv")
print(df)

