# -*- coding: utf-8 -*-
"""ImageToArrayandArrayToImage.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zSmvQLjTGx5pb7XVB92ItPQOByYif8Wz
"""

#image to array
from PIL import Image
import numpy as np
im = Image.open("cat.jpg")
#Show actual Image
display(im)
img_arr = np.array(im)
#print(img_arr)
c=img_arr.size
print(c)
d=type(img_arr)
print(d)
print(img_arr.shape)


#array to image
from PIL import Image
import numpy as np
img = Image.fromarray(img_arr)
display(img)
img.save("RGB_image.jpg")