# -*- coding: utf-8 -*-
"""loadImagefromfille.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zSmvQLjTGx5pb7XVB92ItPQOByYif8Wz
"""

import cv2
import numpy as np

# Load an image from file
img = cv2.imread('zebra.jpg')


# Convert the image to a NumPy array
img_array = np.array(img)

# Print the shape of the array
print(img_array.shape)
print(img_array.size)
print(img_array)


import cv2
import numpy as np

# Load an image from file
img = cv2.imread('zebra.jpg')


# Convert the image to a NumPy array
img_array = np.array(img)
img_array1=img_array+10
img = cv2.cvtColor(img_array1, cv2.COLOR_BGR2RGB)#array to Image

# Display the image with matplotlib
plt.imshow(img)
plt.axis('off')
plt.show()