# -*- coding: utf-8 -*-
"""Smile.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pDQW6wdi335YLBtqEO_WofoA3EWuWmbw
"""

a1 = "\U0001F600"  # Grinning face
a2 = "\U0001F601"  # Beaming face
a3 = "\U0001F602"  # Grinning face with big eyes
a4 = "\U0001F603"  # Grinning face with smiling eyes
a5 = "\U0001F604"  # Smiling face with heart eyes
a6 = "\U0001F605"  # Smiling face with smiling eyes
a7 = "\U0001F606"  # Grinning face
a8 = "\U0001F607"  # Grinning face with big eyes
a9 = "\U0001F608"  # Smiling face
a10 = "\U0001F609"  # Smiling face with smiling eyes
a11 = "\U0001F60A"  # Smiling face
a12 = "\U0001F60B"  # Smiling face
a13 = "\U0001F60C"  # Smiling face
a14 = "\U0001F60D"  # Heart eyes
a15 = "\U0001F60E"  # Smiling face
a16 = "\U0001F60F"  # Smiling face
a17 = "\U0001F610"  # Neutral face
a18 = "\U0001F611"  # Expressionless face
a19 = "\U0001F612"  # Unamused face
a20 = "\U0001F613"  # Face with cold sweat
a21 = "\U0001F614"  # Disappointed face
a22 = "\U0001F615"  # Worried face
a23 = "\U0001F616"  # Angry face
a24 = "\U0001F617"  # Fearful face
a25 = "\U0001F618"  # Weeping face
a26 = "\U0001F619"  # Face with open mouth
a27 = "\U0001F620"  # Grimacing face
a28 = "\U0001F621"  # Confused face
a29 = "\U0001F622"  # Disgusted face
a30 = "\U0001F923"  # Rolling on the floor laughing
a31 = "\U0001F924"  # Grinning face
a32 = "\U0001F925"  # Grinning face
a33 = "\U0001F926"  # Grinning face
a34 = "\U0001F927"  # Smiling face
a35 = "\U0001F928"  # Smiling face
a36 = "\U0001F929"  # Winking face
a37 = "\U0001F92A"  # Smiling face
a38 = "\U0001F92B"  # Smiling face
a39 = "\U0001F92C"  # Grinning face
a40 = "\U0001F92D"  # Grinning face
a41 = "\U0001F92E"  # Grinning face
a42 = "\U0001F92F"  # Grinning face
a43 = "\U0001F930"  # Smiling face
a44 = "\U0001F931"  # Smiling face
a45 = "\U0001F932"  # Smiling face
a46 = "\U0001F933"  # Smiling face
a47 = "\U0001F934"  # Smiling face
a48 = "\U0001F935"  # Smiling face
a49 = "\U0001F936"  # Smiling face
a50 = "\U0001F937"  # Smiling face