# -*- coding: utf-8 -*-
"""vdot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zSmvQLjTGx5pb7XVB92ItPQOByYif8Wz
"""

#V Dot(normal mutiply)

#A and B  V Dot
#1   2	         11   12
#3   4          13   14

#(A11xB11)  +  (A12xB12)  +  (A21xB21)  + (A22xB22)
#Note − 1*11 + 2*12 + 3*13 + 4*14 = 130


import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array([[11,12],[13,14]])
c= np.vdot(a,b)
print(c)

import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array([[11,12],[13,14]])
c= np.vdot(a,b)
print(c)

#V Dot(normal mutiply)

#A and B  V Dot
#1   2	         11   12
#3   4          13   14

#(A11xB11)  +  (A12xB12)  +  (A21xB21)  + (A22xB22)
#Note − 1*11 + 2*12 + 3*13 + 4*14 = 130


import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array([[11,12],[13,14]])
c= np.vdot(a,b)
print(c)