# -*- coding: utf-8 -*-
"""Sentiment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pDQW6wdi335YLBtqEO_WofoA3EWuWmbw
"""

rom textblob import TextBlob
text = "I love this product! It's amazing!"
blob = TextBlob(text)

# Get sentiment polarity (-1 to 1, where -1 is very negative, 0 is neutral, and 1 is very positive)
polarity = blob.sentiment.polarity

# Classify sentiment
if polarity > 0:
  print("positive")
elif polarity < 0:
  print("negative")
else:
  print("neutral")
print(polarity)


from textblob import TextBlob
text = input("enter=")
blob = TextBlob(text)

# Get sentiment polarity (-1 to 1, where -1 is very negative, 0 is neutral, and 1 is very positive)
polarity = blob.sentiment.polarity

# Classify sentiment
if polarity > 0:
  print("positive")
elif polarity < 0:
  print("negative")
else:
  print("neutral")
print(polarity)


from textblob import TextBlob
text = input("enter=")
blob = TextBlob(text)

# Get sentiment polarity (-1 to 1, where -1 is very negative, 0 is neutral, and 1 is very positive)
polarity = blob.sentiment.polarity
print(polarity)

#sentiment analysis
from transformers import pipeline

# Load the sentiment analysis pipeline with a specific model
sentiment_analysis = pipeline("sentiment-analysis", model="nlptown/bert-base-multilingual-uncased-sentiment")

# Text to analyze
text = "I love using Hugging Face Transformers!"

# Analyze sentiment
result = sentiment_analysis(text)

# Print the result
print(result)

from transformers import pipeline

# Load the sentiment analysis pipeline with a specific model
sentiment_analysis = pipeline("sentiment-analysis", model="nlptown/bert-base-multilingual-uncased-sentiment")

# Text to analyze
text = "I dont like Java"

# Analyze sentiment
result = sentiment_analysis(text)

# Store the sentiment score in a variable
score = result[0]['score']

# Print the result
print("Sentiment Score:", score)


#star
from transformers import pipeline

# Load the sentiment analysis pipeline with a specific model
sentiment_analysis = pipeline("sentiment-analysis", model="nlptown/bert-base-multilingual-uncased-sentiment")

# Text to analyze
text = "I dont like Java"

# Analyze sentiment
result = sentiment_analysis(text)

# Store the sentiment label in a variable
label = result[0]['label']

# Print the result
print("Sentiment Label:", label)

On Monday, December 16, 2024 at 8:55:28 AM UTC+5:30 Bala Bala wrote:
#sentiment analysis
from transformers import pipeline

# Load the sentiment analysis pipeline with a specific model
sentiment_analysis = pipeline("sentiment-analysis", model="nlptown/bert-base-multilingual-uncased-sentiment")

# Text to analyze
text = "I love using Hugging Face Transformers!"

# Analyze sentiment
result = sentiment_analysis(text)

# Print the result
print(result)