# -*- coding: utf-8 -*-
"""Sentiment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pDQW6wdi335YLBtqEO_WofoA3EWuWmbw
"""

rom textblob import TextBlob
text = "I love this product! It's amazing!"
blob = TextBlob(text)

# Get sentiment polarity (-1 to 1, where -1 is very negative, 0 is neutral, and 1 is very positive)
polarity = blob.sentiment.polarity

# Classify sentiment
if polarity > 0:
  print("positive")
elif polarity < 0:
  print("negative")
else:
  print("neutral")
print(polarity)


from textblob import TextBlob
text = input("enter=")
blob = TextBlob(text)

# Get sentiment polarity (-1 to 1, where -1 is very negative, 0 is neutral, and 1 is very positive)
polarity = blob.sentiment.polarity

# Classify sentiment
if polarity > 0:
  print("positive")
elif polarity < 0:
  print("negative")
else:
  print("neutral")
print(polarity)


from textblob import TextBlob
text = input("enter=")
blob = TextBlob(text)

# Get sentiment polarity (-1 to 1, where -1 is very negative, 0 is neutral, and 1 is very positive)
polarity = blob.sentiment.polarity
print(polarity)