# -*- coding: utf-8 -*-
"""KNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zSmvQLjTGx5pb7XVB92ItPQOByYif8Wz
"""

x = [1,  2, 3,  4,   5,  6,  7 ,  8,  9,   10]
y = [10, 20, 30, 40, 50, 60, 70 , 80, 90, 100]
c = [0,  0,  0,  0,  0,  1,  1,   1,  1,  1]
from sklearn.neighbors import KNeighborsClassifier
data = list(zip(x, y))
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(data, c)
a=float(input("enter x value"))
b=float(input("enter y value"))
new_x = a
new_y = b
new_point = [(new_x, new_y)]
prediction = knn.predict(new_point)
print("Predited class is",prediction)