# -*- coding: utf-8 -*-
"""Spacy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zSmvQLjTGx5pb7XVB92ItPQOByYif8Wz
"""

#extract name
import spacy

# Load the spaCy English model
nlp = spacy.load("en_core_web_sm")

# Sample sentence
sentence = "On March 15, 2024, John, an experienced software engineer,will receive  $5,000 for his project and Rs 2 lakh for additional services."

# Process the sentence with spaCy
doc = nlp(sentence)

# Extract names (entities labeled as PERSON)
names = [ent.text for ent in doc.ents if ent.label_ == "PERSON"]

print("Extracted Names:", names)

#Verb
import spacy

# Load the spaCy English model
nlp = spacy.load("en_core_web_sm")

# Sample sentence
sentence = "On March 15, 2024, John, an experienced software engineer,will receive  $5,000 for his project and Rs 2 lakh for additional services."

# Process the sentence with spaCy
doc = nlp(sentence)

# Store all verbs in a list
verbs = [token.text for token in doc if token.pos_ == "VERB"]

# Print the extracted verbs
print("Extracted Verbs:", verbs)


#Extracted Nouns
import spacy

# Load the spaCy English model
nlp = spacy.load("en_core_web_sm")

# Sample sentence
sentence = "On March 15, 2024, John, an experienced software engineer,will receive  $5,000 for his project and Rs 2 lakh for additional services."

# Process the sentence with spaCy
doc = nlp(sentence)

# Store all nouns in a list
nouns = [token.text for token in doc if token.pos_ == "NOUN"]

# Print the extracted nouns
print("Extracted Nouns:", nouns)


#extracted adjectives
import spacy

# Load the spaCy English model
nlp = spacy.load("en_core_web_sm")

# Sample sentence
sentence = "On March 15, 2024, John, an experienced software engineer,will receive  $5,000 for his project and Rs 2 lakh for additional services."

# Process the sentence with spaCy
doc = nlp(sentence)

# Store all adjectives in a list
adjectives = [token.text for token in doc if token.pos_ == "ADJ"]

# Print the extracted adjectives
print("Extracted Adjectives:", adjectives)


import spacy

# Load the spaCy English model
nlp = spacy.load("en_core_web_sm")

# Sample sentence
sentence = "On March 15, 2024, John, an experienced software engineer,will receive  $5,000 for his project and Rs 2 lakh for additional services."

# Process the sentence with spaCy
doc = nlp(sentence)

# Store all pronouns in a list
pronouns = [token.text for token in doc if token.pos_ == "PRON"]

# Print the extracted pronouns
print("Extracted Pronouns:", pronouns)


import spacy

# Load the spaCy English model
nlp = spacy.load("en_core_web_sm")

# Sample sentence
sentence = "On March 15, 2024, John, an experienced software engineer,will receive  $5,000 for his project and Rs 2 lakh for additional services."

# Process the sentence with spaCy
doc = nlp(sentence)

# Extract dates from the named entities
dates = [ent.text for ent in doc.ents if ent.label_ == "DATE"]

# Print the extracted dates
print("Extracted Dates:", dates)

import spacy

# Load the spaCy English model
nlp = spacy.load("en_core_web_sm")

# Sample sentence
sentence = "John from TATA India is working in Apple now "
# Process the sentence with spaCy
doc = nlp(sentence)

# Extract organizations from the named entities
organizations = [ent.text for ent in doc.ents if ent.label_ == "ORG"]

# Print the extracted organizations
print("Extracted Organizations:", organizations)