# -*- coding: utf-8 -*-
"""DecisionTree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zSmvQLjTGx5pb7XVB92ItPQOByYif8Wz
"""

import pandas as pd
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
import matplotlib.pyplot as plt

df = pd.read_csv("diabetes.csv")

# Define the features and target variable
features = ['Pregnancies', 'Glucose', 'Pressure', 'Skin', 'Insulin', 'BMI', 'Diabetes', 'Age']
X = df[features]
y = df['Outcome']

# Train the decision tree classifier
dtree = DecisionTreeClassifier()
dtree = dtree.fit(X, y)

# Plot the decision tree
tree.plot_tree(dtree, feature_names=features)

# Make a prediction using a DataFrame with the correct feature names
input_data = pd.DataFrame([[6, 148, 72, 35, 0, 33, 0.62, 50]], columns=features)
prediction = dtree.predict(input_data)

# Output the predicted class
a = prediction[0]
print("Predicted class", a)

from math import e
import pandas as pd
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
import matplotlib.pyplot as plt

# Load the dataset
df = pd.read_csv("diabetes.csv")

# Define the features and target variable
features = ['Pregnancies', 'Glucose', 'Pressure', 'Skin', 'Insulin', 'BMI', 'Diabetes', 'Age']
X = df[features]
y = df['Outcome']

# Train the decision tree classifier
dtree = DecisionTreeClassifier()
dtree = dtree.fit(X, y)

# Plot the decision tree
tree.plot_tree(dtree, feature_names=features)
a=float(input("Enter Pregnancies:"))
b=float(input("Enter Glucose:"))
c=float(input("Enter Pressure:"))
d=float(input("Enter Skin:"))
e=float(input("Enter Insulin:"))
f=float(input("Enter BMI:"))
g=float(input("Enter Diabetes:"))
h=float(input("Enter Age:"))
# Make a prediction using a DataFrame with the correct feature names
input_data = pd.DataFrame([[a, b, c, d, e, f, g, h]], columns=features)
prediction = dtree.predict(input_data)

# Output the predicted class
a = prediction[0]
print("Predicted class", a)