# -*- coding: utf-8 -*-
"""PythonRe1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sKocllROYRFoPtjAYMiPW2jgqhoKV2n7
"""

import re # remove numbers
text = input("Input =")
a=re.sub(r'\d+', '', text)
print(a)

#Lower
b=input("Enter a text")
x1=b.lower()
print(x1)

#upper
b1=input("Enter a text")
x2=b1.upper()
print(x2)

#title
b2=input("Enter a text")
x3=b2.title()
print(x3)

#puntuation
import re
x11=input("Enter a text=")
# Use regular expression to remove punctuation
a1 = re.sub(r'[^\w\s]', '', x11)
print(a1)

#Special cha
import re
text = input("Input =")
a12=re.sub(r'[^A-Za-z0-9\s]+', '', text)
print(a12)

#Remove Extra Whitespaces
import re
text = input("Input =")
a12=re.sub(r'\s+', ' ', text).strip()
print(a12)

pip install fuzzywuzzy

