# -*- coding: utf-8 -*-
"""PythonRe.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sKocllROYRFoPtjAYMiPW2jgqhoKV2n7
"""

import re

txt = "Heavy rain in TN"
x = re.split("\s", txt)
print(x)

import re
with open("python.txt", "r") as file :
    file_contents = file.read()
    x=  re.split("\s" , file_contents)
a=x
print(a)


import re#multi word
txt = "The rain in Spain falls mainly in the plain!"
#Check if the string contains either "falls" or "stays":
x = re.findall("falls|stays", txt)
print(x)
if x:
  print("Yes, there is at least one match!")
else:
  print("No match")


import re#multi word
txt = "The rain in Spain falls mainly in the plain!"
#Check if the string contains either "falls" or "stays":
x = re.findall("falls|Spain|sta", txt)
print(x)
if x:
  print("Yes, there is at least one match!")
else:
  print("No match")


#fisrst  and last
import re
txt = "hi planet hello bala"
# Check if the string starts with 'hello'
x = re.findall("^hello", txt)
print(x)
if x:
    print("Yes, the string starts with 'hello'")
else:
    print("No match")
# Check if the string ends with 'bala'
y = re.findall("bala$", txt)
print(y)
if y:
    print("Yes, the string ends with 'bala'")
else:
    print("No match")


import re
txt = "Heavy rain in TN"
x = re.split("\s", txt)
print(x)

text = " ".join(x)
print(text)

pip install fuzzywuzzy

