# -*- coding: utf-8 -*-
"""ReSplitandJoin.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pDQW6wdi335YLBtqEO_WofoA3EWuWmbw
"""

import re

text = " ".join(x)
print(text)

import re

txt = "Heavy rain in TN"
x = re.split("\s", txt)
print(x)

text = " ".join(x)
print(text)