# -*- coding: utf-8 -*-
"""ReSplit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pDQW6wdi335YLBtqEO_WofoA3EWuWmbw
"""

import re

txt = "Heavy rain in TN"
x = re.split("\s", txt)
print(x)