# -*- coding: utf-8 -*-
"""ReWithFirstLast.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pDQW6wdi335YLBtqEO_WofoA3EWuWmbw
"""

import re

text = " ".join(x)
print(text)

#fisrst  and last
import re

txt = "hi planet hello bala"

# Check if the string starts with 'hello'
x = re.findall("^hello", txt)
print(x)
if x:
    print("Yes, the string starts with 'hello'")
else:
    print("No match")

# Check if the string ends with 'bala'
y = re.findall("bala$", txt)
print(y)
if y:
    print("Yes, the string ends with 'bala'")
else:
    print("No match")