# -*- coding: utf-8 -*-
"""ReWithFileRead.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pDQW6wdi335YLBtqEO_WofoA3EWuWmbw
"""

import re

text = " ".join(x)
print(text)

import re
with open("python.txt", "r") as file :
    file_contents = file.read()
    x=  re.split("\s" , file_contents)


a=x
print(a)