# -*- coding: utf-8 -*-
"""GoogleTranslate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pDQW6wdi335YLBtqEO_WofoA3EWuWmbw
"""

pip install googletrans==4.0.0-rc1

#en english es spanish
from googletrans import Translator

t = Translator()
a = "Hello, how are you?"
translated_text = t.translate(a, src='en', dest='es')
b=translated_text.text
print(b)

#en english es spanish
from googletrans import Translator

t = Translator()
a = "Hello, how are you?"
translated_text = t.translate(a, src='en', dest='ta')
b=translated_text.text
print(b)