# -*- coding: utf-8 -*-
"""GoogleTranslateWithFewLanguages.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pDQW6wdi335YLBtqEO_WofoA3EWuWmbw
"""

Here are some language codes for a few languages:

en: English
es: Spanish
fr: French
de: German
it: Italian
pt: Portuguese
ja: Japanese
ko: Korean
zh: Chinese (Mandarin)
ru: Russian
ar: Arabic
hi: Hindi
ta: Tamil
te: Telugu
bn: Bengali
ur: Urdu
gu: Gujarati
mr: Marathi
kn: Kannada'''

On Wednesday, December 11, 2024 at 9:26:49 AM UTC+5:30 Bala Bala wrote:
pip install googletrans==4.0.0-rc1

#en english es spanish
from googletrans import Translator

t = Translator()
a = "Hello, how are you?"
translated_text = t.translate(a, src='en', dest='es')
b=translated_text.text
print(b)

#en english es spanish
from googletrans import Translator

t = Translator()
a = "Hello, how are you?"
translated_text = t.translate(a, src='en', dest='ta')
b=translated_text.text
print(b)