# -*- coding: utf-8 -*-
"""AudioToText.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zSmvQLjTGx5pb7XVB92ItPQOByYif8Wz
"""

#audio to text
"""To install the SpeechRecognition library using pip, run the following command:

pip install SpeechRecognition

Additionally, you'll also need to install the PyAudio library, which is a cross-platform Python library for audio processing:

pip install pyaudio"""
import speech_recognition as sr

# Initialize the recognizer
recognizer = sr.Recognizer()

# Use the microphone as the audio source
with sr.Microphone() as source:
    print("Adjusting for background noise... Please wait.")
    recognizer.adjust_for_ambient_noise(source, duration=2)
    print("Listening... Speak something!")
    audio = recognizer.listen(source)

# Convert speech to text using Google Speech Recognition

print("Recognizing...")
text = recognizer.recognize_google(audio)
print("You said:", text)