# -*- coding: utf-8 -*-
"""LinearRegression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zSmvQLjTGx5pb7XVB92ItPQOByYif8Wz
"""

#pre
from scipy import stats
x = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
y = [10,20,30,40,50,60,70,80,90,100,110,120,130,140,150,160,170,180,190,200]
slope, intercept, r, p, std_err = stats.linregress(x, y)
x=float(input("enter value to be predicted"))
ypred = slope * x + intercept
print(ypred)