# -*- coding: utf-8 -*-
"""LogicalRegression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zSmvQLjTGx5pb7XVB92ItPQOByYif8Wz
"""

import numpy
from sklearn import linear_model

#Reshaped for Logistic function.
X = numpy.array([50, 52, 55, 60, 61, 62, 70, 75, 76, 77, 80, 88]).reshape(-1,1)
y = numpy.array([0,  0,   0,  0,  0,  0,  1,  1,  1,  1,  1,  1])

logr = linear_model.LogisticRegression()
logr.fit(X,y)
a=float(input("enter value to be predicted ="))
predicted = logr.predict(numpy.array([a]).reshape(-1,1))
print(" predicted value =",predicted)