# -*- coding: utf-8 -*-
"""Filecode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sKocllROYRFoPtjAYMiPW2jgqhoKV2n7
"""

# Open a file for writing
with open('greeting.txt', 'w') as file:

    file.write('Hi how are u .....')

    # Open the file in read-only mode
with open("greeting.txt", "r") as file:

    # Read the contents of the file
    file_contents = file.read()

    # Print the contents of the file
    print(file_contents)

    #append
for i in range(3):
    with open('d2.txt', 'a') as file:# a rep append
        # Write "Hi how are you" to the file
        x = input("text to write=")
        file.write(x + '\n''\n')  # x Adding a newline for better separation of lines


# Open the file in read-only mode
with open("d2.txt", "r") as file:

    # Read the contents of the file
    file_contents = file.read()

    # Print the contents of the file
    print(file_contents)

pip install fuzzywuzzy

